### ISSUE TITLE
Weblate bug causes data loss for translations

### ISSUE THREAD

**Issue by ieugen** [WeblateOrg/weblate#1426]
### Steps to reproduce

I don't know yet.

### Actual behaviour

1. We have 4 projects with ~ 4-7 components each. We use java properties UTF-8 as source.
2. Translators use platform on a daily basis for translating with moderate usage.
3. We have a component that has a lot of strings 5547. At some point for Spanish language the translation file in git is damaged:
* either gets truncated to 365 lines (don't know if this is always the same number)
* or it appears to contain a line with `NoneNoneNone` that corrupts the file. I attached a snippet of text [1].

A second problem, probably related to this one is that Weblate displays source strings in a different language (Vietnames) for that component, even though the source is en-US. This happens only after some strings in the project (string 4997/ 5547) [2]. 

[1] [es-ES.properties.txt](https://github.com/WeblateOrg/weblate/files/889392/es-ES.properties.txt)

[2] ![screenshot from 2017-04-03 11-02-31](https://cloud.githubusercontent.com/assets/1050920/24600915/821b2398-185f-11e7-8a6d-50f63b61f535.png)
[3] 
![screenshot from 2017-04-03 11-40-38](https://cloud.githubusercontent.com/assets/1050920/24601680/8a957c46-1862-11e7-80f4-5370ad92b840.png)
![screenshot from 2017-04-03 11-39-16](https://cloud.githubusercontent.com/assets/1050920/24601679/8a9353e4-1862-11e7-9e98-8c4b15b18a17.png)

### Expected behaviour

* Translations in git should not be truncated. 
* Translations should not contain `NoneNoneNone` lines
* Weblate UI should display the proper source text for all strings inthe project

### Server configuration
Server is Debian Jessie stable with latest updates. 

* Weblate weblate-2.12
 * Python 2.7.9
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.2
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2012c
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.1.2
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
The source language display is taken from monolingual base, so you most likely have the Vietnamese file there. I'm just adding validation to catch this at project setup...

As for the NoneNoneNone value, I've just looked at all translations we have on [Hosted Weblate](https://weblate.org/hosting/) and I found nothing like that. I'm not sure if it can have same root cause as above, but it's certainly worth trying.

**Comment by ieugen** [comment]
Thank you for the quick update. Could the `NoneNone` issue be caused by the code processing the java properties file? 

I have attached the PDF for component configuration if it helps. We have Vietnamese but it is not the source language. 

[Component_with_issues.pdf](https://github.com/WeblateOrg/weblate/files/889567/Component_with_issues.pdf)

**Comment by nijel** [comment]
The component setting looks correct. Did you do some changes to the setup after initial import? In case you did, you can try force reloading all files in case there was some change not properly detected by Weblate (in case it's the case, it should be still investigated):

```
./manage.py loadpo --force gr8pi-report-interpretations
``

Alternatively can you please share with me translation files so that I can try reproducing locally?

**Comment by ieugen** [comment]
Thanks for the info. I have ran the command and attached the file [1]. 

I can send you the files. Which ones source + es, source + es + vi? 

By the way, loadpo did reload the translations but Spanish was reset to 6% translated from 100%. This happened becuse the translation contained only 300+ strings.
The way it seems to behave is like this:
- at some point, the file contains NoneNoneNone
- then weblate reloads it or does something because of an event (new translation/ repository maintenance) and it figures out it needs to fix the bad java properties file
- because `NoneNoneNone` should not be there it truncates the file somehow


[1] [weblate_loadpo.txt](https://github.com/WeblateOrg/weblate/files/889731/weblate_loadpo.txt)
![screenshot from 2017-04-03 13-44-19](https://cloud.githubusercontent.com/assets/1050920/24606043/054fbaee-1874-11e7-82a8-71dd47c5f5d2.png)

![screenshot from 2017-04-03 13-49-07](https://cloud.githubusercontent.com/assets/1050920/24606136/63694956-1874-11e7-8687-9da8a3480714.png)
![screenshot from 2017-04-03 13-48-59](https://cloud.githubusercontent.com/assets/1050920/24606135/63691dfa-1874-11e7-920c-881221809f72.png)

**Comment by nijel** [comment]
Indeed file parsing probably stops as that line.

Sending source + es + vi should be good enough for starting. Ideally if you can take them from revision before the NoneNoneNone stuff was added by Weblate. If you don't want to post them publicly here, you can send them by email to michal@cihar.com.

**Comment by nijel** [comment]
Thanks for providing me the test data. I was not able to trigger this during normal operation, but once I intentionally corrupt the properties file (by adding partial line without value), the None values start to add up and the result looks pretty much as what you're getting.

The question however is how you got into this situation.

**Comment by ieugen** [comment]
Hi, glad to hear you managed to replicate. 
I have no idea. This seems to affect only the Spanish account and only for that component. They have just translate there. 

I imagine that there might be one of the following:
- some conversion issues related to charecter encodings
- an issue with the Java Properties file handler and the above

I am not familiar with how Weblate operates but it seems to me that changes are persisted in database as events and then sent to disk. 
Since I saw the changes in the database, I imagine that the problem occurs during the transformation to disk and one of those components it to blame.

**Comment by nijel** [comment]
The additional corruption by adding None strings will be fixed by https://github.com/translate/translate/pull/3607.

There is still question how it started, here are some possible reasons:

* Locking protocol issue in Weblate. In case the file would not be locked when changing it, this is exactly what could happen. I've (again) reviewed this and the locking seems to be done in all needed places. Do you know if all the changes were made by editing in the web interface, file upload or somehow differently?
* Locking not working properly on your (file)system. Can you try running tests for this on your system? In Git checkout that can be done using `./manage.py test --settings weblate.settings_test weblate.trans.tests.test_filelock`
* Buffering issues. This seems unlikely as underlying code does explicitly call `close()` on the saved file.
* Hardware issue. The memory or disk corruption could happen, but I guess you would have noticed them elsewhere as well.

**Comment by ieugen** [comment]
I ran the lock test: 

````
./manage.py test --settings weblate.settings_test weblate.trans.tests.test_filelock
Creating test database for alias 'default'...
.....Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/weblate/weblate/trans/tests/test_filelock.py", line 106, in second_lock
    lock.acquire()
  File "/var/www/weblate/weblate/trans/filelock.py", line 108, in acquire
    raise FileLockException("Timeout occured.")
FileLockException: Timeout occured.
..
----------------------------------------------------------------------
Ran 7 tests in 0.032s

OK
Destroying test database for alias 'default'...
````

**Comment by nijel** [comment]
Thanks, that looks good as well.

**Comment by nijel** [comment]
Did you see any errors from Weblate in that time? I've just realized that in case of some exception during saving the file such corruption could possibly happen. This has been fixed in 3b1372ee8f5e9f671feac00455beed984e15e934.

**Comment by ieugen** [comment]
I did not, but I am not a translator so I can't say for sure what happend. 

Should I update the branch and perform the upgrade with `./manage ...` ?

**Comment by nijel** [comment]
If you have [configured admins](https://docs.weblate.org/en/latest/admin/install.html#production-admins), you would get notification on such error. You can try upgrading, let's see if the corruption will happen again. I'm still not sure this was really the cause...

**Comment by ieugen** [comment]
Thanks. I did receive some emails regarding failure to push to repository. Nothing else. I don't think they are related. 

I don't know if it helps, but we did some changes via git and not Weblate. That still doesn't explain why onliy Spanish and that component.

I will make the upgrade in the next days and get back. I will revoke access to git repo. Please ask again if you need it. 

Thanks again,

**Comment by nijel** [comment]
The changes in git should not cause any problems, the file was obviously corrupted by Weblate commit.

**Comment by ieugen** [comment]
Hello, 

I have deployed the 2.14-dev and re-created all the components and the issue still appear but this time for Norwegian language. 

Some notable things: 
- SIMPLIFY languges is now at default value - `true` I believe
- we have two files: no-NO.properties and no_NO.properties. We are adapting the file names to use weblate format xx_YY (Posix style language tag)

I hope this helps.

**Comment by nijel** [comment]
Can you try upgrading translate-toolkit to git snapshot as well? My fix has been already integrated there...

**Comment by nijel** [comment]
Any luck with trying newer translate-toolkit?

**Comment by ieugen** [comment]
Hello. I did not had the time to upgrade and we eventually split the large component into smaller ones. We also migrated to json file format since I believe it is better supported and tested all around, instead of java properties. 

I'm closing this ticket as we can't duplicate the issue any more.
