### ISSUE TITLE
Compose Multiplatform Resources is not the same as Android resources

### ISSUE THREAD

**Issue by lemcoder** [WeblateOrg/weblate#15091]
### Describe the issue

There are minor differences in CMP resources and Android resources
Refer to:
https://github.com/JetBrains/compose-multiplatform/issues/4664
and
https://github.com/tolgee/tolgee-platform/issues/2397

I think there should be separate format for CMP resources or an option to disable escaping chars wiht '\\'
Right now if You have quotes in translations weblate will escape them resulting in displaying \\" in application

### I already tried

- [x] I've read and searched [the documentation](https://docs.weblate.org/).
- [x] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Add a translation with quotes
2. Download trasnlations XMLs
3. Use in app
4. The escape slash is visible in text displayed on screen

### Expected behavior

Do not add escape slash to CMP resources

### Exception traceback

```pytb

```

### Weblate deploy checks

```shell

```

**Comment by nijel** [comment]
Are these differences documented somewhere? I think I've addressed this particular one at https://github.com/translate/translate/pull/5609, but having the format

Weblate already has "Mobile Kotlin Resource" since 7881e9691e38f575b27c8faed4b4bd07b8bc2b71, but it currently only differs in plurals handling. 

What would be the best name for this?

**Comment by nijel** [comment]
Hmm, actually these are two different formats. https://github.com/translate/translate/pull/5610 should address it on the format level.

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/pull/15133 should address this.

**Comment by lemcoder** [comment]
I've updated to the latest version of Weblate (5.12.2), but the issue still persists. I've also changed the file format in the component settings to "Compose Multiplatform resources".

For example, the French translation displayed in the Weblate UI is:
`Bienvenue dans la version préliminaire de l'application Efento Cloud`
But in the downloaded file, it appears as:
`<string name="cloud_changelogScreen_title">Bienvenue dans la version préliminaire de l\'application Efento Cloud</string>`

As you can see, the apostrophe is still being escaped.

**Comment by nijel** [comment]
Right, this part of the problem was not yet addressed, created https://github.com/translate/translate/issues/5635 to track this.
