### ISSUE TITLE
Working with i18next format gives unexpected file content (pushing to repo and export)

### ISSUE THREAD

**Issue by rtreffler-piwik** [WeblateOrg/weblate#1701]
I've noticed that exporting into i18next JSON files is not working properly.
When in projects polish language I'm choosing `File -> Download original translation file (i18next JSON file)`
This works the same when the code is being pushed to the repository.
Translation in Weblate works properly, I am seeing two plural forms for English and three for Polish language.

Each form instead of having a separate key is put into subarray under the original key.
Subarray has ordinal keys.

So my initial English file is
```
{
  "hello": "Hello",
  "apple": "I have an apple",
  "apple_plural": "I have {{count}} apples",
  "apple_negative": "I have no apples"
}
```
in polish exports to
```
{
  "hello": "Witaj",
  "apple": [
    "Mam jabłko",
    "Mam {{count}} jabłka",
    "Mam {{count}} jabłek"
  ],
  "apple_negative": "Nie mam jabłek"
}
```
instead of
```
{
  "hello": "Witaj",
  "apple": "Mam jabłko",
  "apple_1": "Mam {{count}} jabłka",
  "apple_2": "Mam {{count}} jabłek",
  "apple_negative": "Nie mam jabłek"
}
```
I'm using docker's master branch and I've followed instructions from [here](https://docs.weblate.org/en/latest/admin/deployments.html#docker)

My `weblate list_versions` output:
```
 * Weblate 2.17.1
 * Python 2.7.13
 * Django 1.11.7
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.3
 * pytz 2017.3
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0
 * git-svn 2.11.0
 * hub 2.2.9
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by wichert** [comment]
Shouldn't your original English be

```
{
  "hello": "Hello",
  "apple": "I have an apple",
  "apple_1": "I have {{count}} apples",
  "apple_2": "I have no apples"
}
```

The translation should have the same format as the input.

**Comment by rtreffler-piwik** [comment]
Yes, let me add documentation link for i18next plurals:
https://www.i18next.com/plurals.html

**Comment by nijel** [comment]
Okay, it seems that this is one of the corner cases which I've fixed in https://github.com/translate/translate/pull/3685, at least the tests I've added in https://github.com/translate/translate/pull/3748 fail in earlier versions.

Can you please try patching translate-toolkit with https://github.com/translate/translate/pull/3685 and check if that helps?

**Comment by rtreffler-piwik** [comment]
If I did everything properly (I've replaced /usr/local/lib/python2.7/dist-packages/translate/storage/jsonl10n.py and compiled it to pyc with `python -m compileall json10n.py` and then restarted container with docker-compose up without additional flags)

Unfortunately, it's still not correct, output I'm receiving is
```
{
    "hello": "Witaj",
    "apple[0]": "Mam 1 jabłko",
    "apple[1]": "Mam {{count}} jabłka",
    "apple[2]": "Mam {{count}} jabłek",
    "apple_negative": "Nie mam jabłek",
    "apple": [
        "Mam {{count}} jabłko",
        "Mam {{count}} jabłka",
        "Mam {{count}} jabłek"
    ]
}
```

**Comment by nijel** [comment]
Hmm, I must be doing something different in the test then ... let me check that again.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by rtreffler-piwik** [comment]
I can confirm its working properly.
Thank you for quick response.
