### ISSUE TITLE
msgmerge only called in linked components

### ISSUE THREAD

**Issue by paulpach** [WeblateOrg/weblate#2522]
**Describe the bug**
I have 4 components,  1 primary called UI and 3 other linked ones:
<img width="1091" alt="screen shot 2019-01-25 at 7 11 01 am" src="https://user-images.githubusercontent.com/466007/51748135-1b203680-2071-11e9-8ebc-002b08c9303e.png">

in all of them I have added msgmerge addon:
<img width="1088" alt="screen shot 2019-01-25 at 7 11 35 am" src="https://user-images.githubusercontent.com/466007/51748158-270bf880-2071-11e9-8a1a-a60934ee3115.png">

They are all configured as 
<img width="589" alt="screen shot 2019-01-25 at 7 12 21 am" src="https://user-images.githubusercontent.com/466007/51748169-2ffcca00-2071-11e9-9bf0-237d18b91e94.png">

Notice the custom extension poc,  which I had to do because some of my other tools get confused with po.

I pushed a new string to my UI.pot  file:

```
Pauls-MacBook-Pro:locales Paul$ git diff
diff --git a/UI.pot b/UI.pot
index 85b7fb8..7a53a07 100644
--- a/UI.pot
+++ b/UI.pot
@@ -2775,3 +2775,6 @@ msgstr ""
 
 msgid "Generate Name"
 msgstr ""
+
+msgid "Travel"
+msgstr ""
Pauls-MacBook-Pro:locales Paul$ git add .
Pauls-MacBook-Pro:locales Paul$ git commit -m "Added travel message"
[master 8ccd75a] Added travel message
 1 file changed, 3 insertions(+)
Pauls-MacBook-Pro:locales Paul$ git push
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 320 bytes | 320.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To gitlab.com:blockstory3/Cubica2_i18n.git
   e5840c2..8ccd75a  master -> master
```

The server did not run msgmerge:
```
INFO received GitLab notification on repository https://gitlab.com/blockstory3/Cubica2_i18n, branch master, 1 matching components, 1 to process
INFO GitLab notification will update Cubica/UI
[2019-01-25 13:14:33,535: INFO/MainProcess] Received task: weblate.trans.tasks.perform_update[52d70b3b-2411-4d79-a92f-1db1f604e2fd]  
10.32.0.1 - - [25/Jan/2019:13:14:33 +0000] "POST /hooks/gitlab/ HTTP/1.1" 200 63 "-" "-"
[pid: 151|app: 0|req: 7555/11431] 10.32.0.1 () {44 vars in 656 bytes} [Fri Jan 25 13:14:33 2019] POST /hooks/gitlab/ => generated 63 bytes in 74 msecs (HTTP/1.1 200) 8 headers in 425 bytes (1 switches on core 0)
[2019-01-25 13:14:33,548: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
INFO cubica/ui: updating repository
[2019-01-25 13:14:33,548: INFO/ForkPoolWorker-2] cubica/ui: updating repository
[2019-01-25 13:14:33,550: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
10.32.0.1 - - [25/Jan/2019:13:14:35 +0000] "GET / HTTP/1.1" 200 9200 "-" "GoogleHC/1.0"
[pid: 151|app: 0|req: 7556/11432] 10.32.0.1 () {32 vars in 342 bytes} [Fri Jan 25 13:14:35 2019] GET / => generated 9200 bytes in 35 msecs (HTTP/1.1 200) 11 headers in 680 bytes (1 switches on core 0)
DEBUG git: exec git fetch origin [retcode=0]
[2019-01-25 13:14:36,724: DEBUG/ForkPoolWorker-2] git: exec git fetch origin [retcode=0]
INFO cubica/ui: update took 3.17 seconds
[2019-01-25 13:14:36,724: INFO/ForkPoolWorker-2] cubica/ui: update took 3.17 seconds
DEBUG git: exec git log --format=format:%H ..origin/master -- [retcode=0]
[2019-01-25 13:14:36,746: DEBUG/ForkPoolWorker-2] git: exec git log --format=format:%H ..origin/master -- [retcode=0]
[2019-01-25 13:14:36,800: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
DEBUG git: exec git log -n 1 --format=format:%H HEAD [retcode=0]
[2019-01-25 13:14:36,810: DEBUG/ForkPoolWorker-2] git: exec git log -n 1 --format=format:%H HEAD [retcode=0]
DEBUG git: exec git branch [retcode=0]
[2019-01-25 13:14:36,854: DEBUG/ForkPoolWorker-2] git: exec git branch [retcode=0]
DEBUG git: exec git branch weblate-merge-tmp origin/master [retcode=0]
[2019-01-25 13:14:36,865: DEBUG/ForkPoolWorker-2] git: exec git branch weblate-merge-tmp origin/master [retcode=0]
DEBUG git: exec git checkout weblate-merge-tmp [retcode=0]
[2019-01-25 13:14:36,995: DEBUG/ForkPoolWorker-2] git: exec git checkout weblate-merge-tmp [retcode=0]
DEBUG git: exec git merge --message Merge branch 'origin/master' into Weblate.

 master [retcode=0]
[2019-01-25 13:14:37,005: DEBUG/ForkPoolWorker-2] git: exec git merge --message Merge branch 'origin/master' into Weblate.

 master [retcode=0]
DEBUG git: exec git checkout master [retcode=0]
[2019-01-25 13:14:37,017: DEBUG/ForkPoolWorker-2] git: exec git checkout master [retcode=0]
DEBUG git: exec git merge weblate-merge-tmp [retcode=0]
[2019-01-25 13:14:37,070: DEBUG/ForkPoolWorker-2] git: exec git merge weblate-merge-tmp [retcode=0]
DEBUG git: exec git branch [retcode=0]
[2019-01-25 13:14:37,098: DEBUG/ForkPoolWorker-2] git: exec git branch [retcode=0]
DEBUG git: exec git branch -D weblate-merge-tmp [retcode=0]
[2019-01-25 13:14:37,112: DEBUG/ForkPoolWorker-2] git: exec git branch -D weblate-merge-tmp [retcode=0]
INFO cubica/ui: merge remote into repo
[2019-01-25 13:14:37,113: INFO/ForkPoolWorker-2] cubica/ui: merge remote into repo
10.32.0.1 - - [25/Jan/2019:13:14:37 +0000] "GET / HTTP/1.1" 200 9200 "-" "GoogleHC/1.0"
[pid: 151|app: 0|req: 7557/11433] 10.32.0.1 () {32 vars in 342 bytes} [Fri Jan 25 13:14:37 2019] GET / => generated 9200 bytes in 54 msecs (HTTP/1.1 200) 11 headers in 680 bytes (2 switches on core 0)
10.32.0.1 - - [25/Jan/2019:13:14:37 +0000] "GET / HTTP/1.1" 200 9200 "-" "GoogleHC/1.0"
[pid: 151|app: 0|req: 7558/11434] 10.32.0.1 () {32 vars in 342 bytes} [Fri Jan 25 13:14:37 2019] GET / => generated 9200 bytes in 33 msecs (HTTP/1.1 200) 11 headers in 680 bytes (1 switches on core 0)
[2019-01-25 13:14:38,297: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
[2019-01-25 13:14:38,297: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
DEBUG git: exec git status --porcelain [retcode=0]
[2019-01-25 13:14:38,309: DEBUG/ForkPoolWorker-2] git: exec git status --porcelain [retcode=0]
[2019-01-25 13:14:38,813: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
[2019-01-25 13:14:38,814: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
DEBUG git: exec git status --porcelain [retcode=0]
[2019-01-25 13:14:38,824: DEBUG/ForkPoolWorker-2] git: exec git status --porcelain [retcode=0]
[2019-01-25 13:14:39,029: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
[2019-01-25 13:14:39,030: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
DEBUG git: exec git status --porcelain [retcode=0]
[2019-01-25 13:14:39,047: DEBUG/ForkPoolWorker-2] git: exec git status --porcelain [retcode=0]
[2019-01-25 13:14:39,277: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
[2019-01-25 13:14:39,278: INFO/ForkPoolWorker-2] Lock 139867064327080 acquired on /app/data/vcs/cubica/ui.lock
DEBUG git: exec git status --porcelain [retcode=0]
[2019-01-25 13:14:39,287: DEBUG/ForkPoolWorker-2] git: exec git status --porcelain [retcode=0]
[2019-01-25 13:14:39,288: INFO/ForkPoolWorker-2] Lock 139867064327080 released on /app/data/vcs/cubica/ui.lock
INFO cubica/ui: checking es/UI.poc (es) [1/3]
[2019-01-25 13:14:39,290: INFO/ForkPoolWorker-2] cubica/ui: checking es/UI.poc (es) [1/3]
INFO cubica/ui: checking ru/UI.poc (ru) [2/3]
[2019-01-25 13:14:39,298: INFO/ForkPoolWorker-2] cubica/ui: checking ru/UI.poc (ru) [2/3]
INFO cubica/ui: checking vi/UI.poc (vi) [3/3]
[2019-01-25 13:14:39,304: INFO/ForkPoolWorker-2] cubica/ui: checking vi/UI.poc (vi) [3/3]
INFO cubica/ui: updating linked project Cubica/Item [0/3]
[2019-01-25 13:14:39,317: INFO/ForkPoolWorker-2] cubica/ui: updating linked project Cubica/Item [0/3]
INFO cubica/item: checking es/Item.poc (es) [1/4]
[2019-01-25 13:14:39,320: INFO/ForkPoolWorker-2] cubica/item: checking es/Item.poc (es) [1/4]
INFO cubica/item: checking pt_BR/Item.poc (pt_BR) [2/4]
[2019-01-25 13:14:39,326: INFO/ForkPoolWorker-2] cubica/item: checking pt_BR/Item.poc (pt_BR) [2/4]
INFO cubica/item: checking ru/Item.poc (ru) [3/4]
[2019-01-25 13:14:39,332: INFO/ForkPoolWorker-2] cubica/item: checking ru/Item.poc (ru) [3/4]
INFO cubica/item: checking vi/Item.poc (vi) [4/4]
[2019-01-25 13:14:39,338: INFO/ForkPoolWorker-2] cubica/item: checking vi/Item.poc (vi) [4/4]
INFO cubica/item: updating completed
[2019-01-25 13:14:39,417: INFO/ForkPoolWorker-2] cubica/item: updating completed
INFO cubica/ui: updating linked project Cubica/Skill [1/3]
[2019-01-25 13:14:39,419: INFO/ForkPoolWorker-2] cubica/ui: updating linked project Cubica/Skill [1/3]
INFO cubica/skill: checking es/Skill.poc (es) [1/3]
[2019-01-25 13:14:39,421: INFO/ForkPoolWorker-2] cubica/skill: checking es/Skill.poc (es) [1/3]
INFO cubica/skill: checking ru/Skill.poc (ru) [2/3]
[2019-01-25 13:14:39,428: INFO/ForkPoolWorker-2] cubica/skill: checking ru/Skill.poc (ru) [2/3]
INFO cubica/skill: checking vi/Skill.poc (vi) [3/3]
[2019-01-25 13:14:39,434: INFO/ForkPoolWorker-2] cubica/skill: checking vi/Skill.poc (vi) [3/3]
INFO cubica/skill: updating completed
[2019-01-25 13:14:39,507: INFO/ForkPoolWorker-2] cubica/skill: updating completed
INFO cubica/ui: updating linked project Cubica/Skin [2/3]
[2019-01-25 13:14:39,508: INFO/ForkPoolWorker-2] cubica/ui: updating linked project Cubica/Skin [2/3]
INFO cubica/skin: checking es/Skin.poc (es) [1/3]
[2019-01-25 13:14:39,510: INFO/ForkPoolWorker-2] cubica/skin: checking es/Skin.poc (es) [1/3]
INFO cubica/skin: checking ru/Skin.poc (ru) [2/3]
[2019-01-25 13:14:39,516: INFO/ForkPoolWorker-2] cubica/skin: checking ru/Skin.poc (ru) [2/3]
INFO cubica/skin: checking vi/Skin.poc (vi) [3/3]
[2019-01-25 13:14:39,522: INFO/ForkPoolWorker-2] cubica/skin: checking vi/Skin.poc (vi) [3/3]
INFO cubica/skin: updating completed
[2019-01-25 13:14:39,596: INFO/ForkPoolWorker-2] cubica/skin: updating completed
INFO cubica/ui: running batch check: inconsistent
[2019-01-25 13:14:39,597: INFO/ForkPoolWorker-2] cubica/ui: running batch check: inconsistent
INFO cubica/ui: updating completed
[2019-01-25 13:14:39,725: INFO/ForkPoolWorker-2] cubica/ui: updating completed
DEBUG git: exec git log --format=format:%H origin/master.. -- [retcode=0]
[2019-01-25 13:14:39,750: DEBUG/ForkPoolWorker-2] git: exec git log --format=format:%H origin/master.. -- [retcode=0]
DEBUG git: exec git log --format=format:%H origin/master.. -- [retcode=0]
[2019-01-25 13:14:39,785: DEBUG/ForkPoolWorker-2] git: exec git log --format=format:%H origin/master.. -- [retcode=0]
10.32.0.1 - - [25/Jan/2019:13:15:35 +0000] "GET / HTTP/1.1" 200 9200 "-" "GoogleHC/1.0"
```

**Expected behavior**
I expect msgmerge to run on UI.pot and add the entry to UI.poc in all my languages

**Server configuration and status**

list_versions:
```
DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git review --version [retcode=1]
DEBUG git: exec git svn --version [retcode=0]
DEBUG hg: exec hg version -q [retcode=0]
 * Weblate 3.4
 * Python 3.6.7
 * Django 2.1.5
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.7.5
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.14.65+ (x86_64)
```

check --deploy:
```
$ weblate check --deploy
DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git review --version [retcode=1]
DEBUG git: exec git svn --version [retcode=0]
DEBUG hg: exec hg version -q [retcode=0]
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.4/admin/install.html#collecting-errors

System check identified 4 issues (0 silenced).
```

**Additional context**
It works perfectly if I update any one of the linked components.

**Comment by nijel** [comment]
It might be that the error in the background update is not properly handled, if you're using Docker image, I've just fixed that in https://github.com/WeblateOrg/docker/commit/463af1adcc3f10db0aab701be7a8af030dfc71a1.

**Comment by paulpach** [comment]
Thanks,  I will give that a try

**Comment by paulpach** [comment]
Can you make a 3.4.1 docker image so that I can test this?

**Comment by paulpach** [comment]
I am still having this issue,  msgmerge is not being called on my component.

when I push something I see this:
```
[2019-07-15 21:22:19,487: INFO/MainProcess] Received task: weblate.trans.tasks.perform_update[fbe17930-7bfb-463c-8c65-deb2b92fbd6c]
10.128.0.24 - - [15/Jul/2019:21:22:19 -0500] "POST /hooks/gitlab/ HTTP/1.1" 200 63 "-" "-"
[pid: 193|app: 0|req: 43/81] 10.128.0.24 () {44 vars in 658 bytes} [Mon Jul 15 21:22:19 2019] POST /hooks/gitlab/ => generated 63 bytes in 76 msecs (HTTP/1.1 200) 8 headers in 425 bytes (1 switches on core 0)
[2019-07-15 21:22:19,552: INFO/MainProcess] Lock 139720188923240 acquired on /app/data/vcs/cubica/ui.lock
[2019-07-15 21:22:19,557: INFO/MainProcess] Lock 139720188923240 acquired on /app/data/vcs/cubica/ui.lock
INFO cubica/ui: updating repository
[2019-07-15 21:22:19,750: INFO/MainProcess] cubica/ui: updating repository
[2019-07-15 21:22:19,755: INFO/MainProcess] Lock 139720188923240 acquired on /app/data/vcs/cubica/ui.lock
INFO cubica/ui: update took 1.99 seconds
[2019-07-15 21:22:21,750: INFO/MainProcess] cubica/ui: update took 1.99 seconds
[2019-07-15 21:22:21,781: INFO/MainProcess] Lock 139720188923240 acquired on /app/data/vcs/cubica/ui.lock
INFO cubica/item/es: committing pending changes (update)
[2019-07-15 21:22:22,619: INFO/MainProcess] cubica/item/es: committing pending changes (update)```

Here is my component configuration for ui:

<img width="969" alt="Screen Shot 2019-07-15 at 9 23 59 PM" src="https://user-images.githubusercontent.com/466007/61261270-ebf8a100-a746-11e9-9b8b-4e7970891082.png">

Notice they are gettext po,   but I changed the extension to poc because of conflicts with another tool.

**Comment by nijel** [comment]
I've seen it on https://github.com/WeblateOrg/weblate/issues/2813 as well, but we still haven't found root cause there...
